### ISSUE TITLE
Frontend Framework

### ISSUE THREAD

**Issue by gabru-md** [yogdaan/yogdaan.github.io#1]
Comment down the frontend framework that we must choose for the org website.

If the framework is already added, then simply add a reaction to it.

Thank You!

**Comment by yashovardhanagrawal** [comment]
for now, as discussed in the meeting, we will have a landing page in normal HTML, CSS & JS.

Also, we should discuss the flow of the website, the sections and design which can be implemented for the same. 

CC: @ParthS007 @xeon-zolt @vaibhavsingh97 @dynamitechetan
