### ISSUE TITLE
Lets Improve NAV BAR

### ISSUE THREAD

**Issue by xeon-zolt** [yogdaan/yogdaan.github.io#10]
the navigation bar is currently little less user-friendly 
![screenshot_20180429_221128](https://user-images.githubusercontent.com/4529442/39408844-5003a400-4bfa-11e8-8796-4d9fc5ef654e.png)
Let's keep it that simple yet more user-friendly 
I was thinking something like -- > https://codepen.io/xeon006/pen/YLNxzV?editors=1100
![screenshot_20180429_221232](https://user-images.githubusercontent.com/4529442/39408863-817c6daa-4bfa-11e8-88f8-cd38400989c2.png)

**Comment by Manas-kashyap** [comment]
i am taking this

**Comment by xeon-zolt** [comment]
@Manas-kashyap I have already solved most part of the issue you just need to add 2 SVG one for telegram and one for join us and add the CSS for nav bar and nav bar to the index.html

**Comment by Manas-kashyap** [comment]
sure , it will be done by tommorow.

**Comment by gabru-md** [comment]
@Manas-kashyap update please?

**Comment by xeon-zolt** [comment]
@gabru-md as @Manas-kashyap did nothing for last 7 days I took up the issue

**Comment by xeon-zolt** [comment]
#13 I think we should make how long one can be assigned a issue too in best practices

**Comment by Manas-kashyap** [comment]
@xeon-zolt i am busy with my end sem exams , plus , the .deb packaging of , livewall , give me time , or if someone can take pls do so , as i won't be free before 11 May .

**Comment by Ananthavijay** [comment]
I made some little changes @xeon-zolt . [check it here]( https://codepen.io/Ananthavijay/pen/qYoWMv) .Thanks
