### ISSUE TITLE
Website is not good for Mobile 

### ISSUE THREAD

**Issue by Ananthavijay** [yogdaan/yogdaan.github.io#11]

**Comment by Manas-kashyap** [comment]
Whats the error ? can you please post the screenshot here

**Comment by nityanandagohain** [comment]
@Ananthavijay since we are not using bootstrap or any other libraries the aligning of the bottom is not propers there are some bugs. Thanks for pointing it out . Please go ahead if you want to fix it.

**Comment by Ananthavijay** [comment]
I will try

**Comment by Ananthavijay** [comment]
now it is perfect
