### ISSUE TITLE
What is this org about?

### ISSUE THREAD

**Issue by palash25** [yogdaan/yogdaan.github.io#2]
Can I get a little more info on what is this organization about, the kind of projects to be undertaken and how to join/participate?

**Comment by gabru-md** [comment]
[https://orgmanager.miguelpiedrafita.com/join/38074740](https://orgmanager.miguelpiedrafita.com/join/38074740)

Please follow this link to join the organization.
The main aim of organization is to promote open source and build projects.
We also like to bring new people into this community by working with them. Moreover, we aim to stabilize the pre-built projects of various organizations into making them even better.

You can help us make this community better, by contributing and participating in the daily discussions.

We look forward to have you here
:)

**Comment by palash25** [comment]
thanks @gabru-md  :+1:

**Comment by midopooler** [comment]
@gabru-md As I can check the given link is not working (https://orgmanager.miguelpiedrafita.com/join/38074740)
Can you invite me to the org manually?
