### ISSUE TITLE
loading page

### ISSUE THREAD

**Issue by Ananthavijay** [yogdaan/yogdaan.github.io#28]
I think having a loading page would be nice. We can have an animation with our logo instead of some svg's.
What u say guys?

**Comment by xeon-zolt** [comment]
@Ananthavijay I think it would be nice till rest of the webpage loads but currently, page is light enough so loading animation will be like a bloat here but if you want to work on it feel free to work cause that can be used later too or in projects that require loading animation

**Comment by Ananthavijay** [comment]
Logo animation is done.. check it here : https://codepen.io/Ananthavijay/pen/RYjZdr .
And give some color codes for the strokes to look better. What are your views guys?

**Comment by Ananthavijay** [comment]
Closing this issue. As this will be included in artworks repo!
