### ISSUE TITLE
Telegram Link Broken

### ISSUE THREAD

**Issue by Yashank18** [yogdaan/yogdaan.github.io#34]
#### Screenshot
![Screenshot (135)](https://user-images.githubusercontent.com/46098062/80629330-5083b300-8a70-11ea-9297-cb4c6fd36459.png)

**Comment by xeon-zolt** [comment]
Just checked it's working, their might be some other issues I think have you tested any other t.me link ?

**Comment by Yashank18** [comment]
@xeon-zolt Yes, I resolved it, it was an issue with my browser. 
Closing this Issue.
