### ISSUE TITLE
Redundant CSS

### ISSUE THREAD

**Issue by gabru-md** [yogdaan/yogdaan.github.io#4]
The same CSS is written into the `index.html` page and the `style.css` as well.
Please remove the redundant CSS from the `index.html` page and verify if the page remains the same.

It is a beginner friendly issue and can be easily solved.

Cheers!

**Comment by nityanandagohain** [comment]
can i pick it up ?? :sweat_smile: :

**Comment by gabru-md** [comment]
Sure! 
Please send a PR to fix this  :)
