### ISSUE TITLE
Add links to bottom bar

### ISSUE THREAD

**Issue by gabru-md** [yogdaan/yogdaan.github.io#6]
Add the following links to the footer of the page

- Telegram Join Link
- Gitter Join Link
- Github Link for Organisation

**Comment by nityanandagohain** [comment]
Can i claim this

**Comment by gabru-md** [comment]
Sure do

**Comment by nityanandagohain** [comment]
@gabru-md please provide me the telegram link

**Comment by gabru-md** [comment]
t.me/yogdaan
