### ISSUE TITLE
Build seems to have failed

### ISSUE THREAD

**Issue by gabru-md** [yogdaan/yogdaan.github.io#9]

**Comment by xeon-zolt** [comment]
?? Details Sir

**Comment by gabru-md** [comment]
![buildfailed](https://user-images.githubusercontent.com/25414121/39408948-eca0caee-4bfb-11e8-8dd4-7c3890500703.png)

Here is what I received as a email

**Comment by xeon-zolt** [comment]
@gabru-md join us not visible also solved

**Comment by gabru-md** [comment]
Yes, It was not visible due to build failure of github pages. Now the changes are visible. Therefore closing this issue :)
